# Generated by Django 4.2.10 on 2025-03-09 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Oyun Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("draw_guess", "Çiz & Tahmin Et"),
                            ("actor_movie", "Aktör & Film"),
                            ("movie_quiz", "Film Bilgi Yarışması"),
                            ("movie_puzzle", "Film Bulmaca"),
                        ],
                        max_length=50,
                        verbose_name="Oyun Tipi",
                    ),
                ),
                (
                    "max_players",
                    models.IntegerField(default=4, verbose_name="Maksimum Oyuncu"),
                ),
                (
                    "min_players",
                    models.IntegerField(default=2, verbose_name="Minimum Oyuncu"),
                ),
                (
                    "duration",
                    models.IntegerField(default=15, verbose_name="Süre (dakika)"),
                ),
                (
                    "points",
                    models.IntegerField(default=100, verbose_name="Kazanılacak Puan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Oyun",
                "verbose_name_plural": "Oyunlar",
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Puan")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_ready", models.BooleanField(default=False, verbose_name="Hazır")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Oyuncu",
                "verbose_name_plural": "Oyuncular",
            },
        ),
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Oda Adı")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Bekliyor"),
                            ("playing", "Oynanıyor"),
                            ("finished", "Tamamlandı"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Özel Oda"),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=50, verbose_name="Şifre"),
                ),
                ("max_players", models.IntegerField(verbose_name="Maksimum Oyuncu")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="games.game",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyun Odası",
                "verbose_name_plural": "Oyun Odaları",
            },
        ),
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(verbose_name="Tur Numarası")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "word",
                    models.CharField(blank=True, max_length=255, verbose_name="Kelime"),
                ),
                (
                    "drawing_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Çizim Verisi"
                    ),
                ),
                (
                    "current_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_rounds",
                        to="games.gameplayer",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.person",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="games.gameroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyun Turu",
                "verbose_name_plural": "Oyun Turları",
                "ordering": ["round_number"],
            },
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="games.gameroom",
            ),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GameGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guess", models.CharField(max_length=255, verbose_name="Tahmin")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Doğru"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Kazanılan Puan"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="games.gameplayer",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="games.gameround",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahmin",
                "verbose_name_plural": "Tahminler",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_system_message",
                    models.BooleanField(default=False, verbose_name="Sistem Mesajı"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="games.gameplayer",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="games.gameroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sohbet Mesajı",
                "verbose_name_plural": "Sohbet Mesajları",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(max_length=50, verbose_name="Başarı Tipi"),
                ),
                ("value", models.IntegerField(default=0, verbose_name="Değer")),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyun Başarısı",
                "verbose_name_plural": "Oyun Başarıları",
            },
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("room", "user")},
        ),
    ]
